name: MedicalImageProcessing
version: 0.1.0.0
github: "petals-of-white/medical-image-processing-haskell"
license: MIT
author: "Maksym Syvash"
maintainer: "maksym_syvash@outlook.com"
copyright: "2024 Maksym Syvash"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category: Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/petals-of-white/medical-image-processing-haskell#readme>

language: GHC2021

dependencies:
  - base >= 4.7 && < 5
  - monomer
  - tinyfiledialogs
  - text
  - text-show
  - lens
  - friday
  - hs-dicom
  - bytestring
  - binary
  - bytestring-to-vector
  - either
  - convertible
  - vector

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  MedicalImageProcessing-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    dependencies:
      - MedicalImageProcessing

tests:
  MedicalImageProcessing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
    dependencies:
      - MedicalImageProcessing
